### PR TITLE
LW1_VAR19 Added

### PR DESCRIPTION
**Pull request by otkisyan**
Добавил 19 вариант

### CODE REVIEW

**Review by Mackasin — COMMENTED** [review]
where is your Main file?

**Comment by otkisyan** [comment]
I thought that I don't need to include my Main file here, because we have the same Main files

**Comment by Mackasin** [comment]
ok, I will aprove your pull request

**Comment by otkisyan** [comment]
Thank you

**Review by Mackasin — APPROVED** [review]

**Pull request merged**
